### ISSUE TITLE
Crashes when used in viewpager

### ISSUE THREAD

**Issue by rjain90** [gotokatsuya/KenBurnsView#8]
Crashes when swipe left or right in a view pager.

<java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
                                                                       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                       at java.util.ArrayList.get(ArrayList.java:308)
                                                                       at com.goka.kenburnsview.KenBurnsView.loadByGlide(KenBurnsView.java:423)
                                                                       at com.goka.kenburnsview.KenBurnsView.loadImage(KenBurnsView.java:392)
                                                                       at com.goka.kenburnsview.KenBurnsView.autoSwapImage(KenBurnsView.java:209)
                                                                       at com.goka.kenburnsview.KenBurnsView.access$000(KenBurnsView.java:22)
                                                                       at com.goka.kenburnsview.KenBurnsView$1.run(KenBurnsView.java:274)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)>

**Comment by rjain90** [comment]
The number of imageViews don't change when changing the number of images.

**Comment by rjain90** [comment]
It crashes when used in a viewpager as sCachedSizeForLoadType is static and its value changes when viewpager loads the next item in advance.
